---

- name: Initial Setup
  hosts: localhost

  vars:
    minimum_ansible_version: "2.7"
    # using versioned pips requires 2.7

    packages:
      - libffi-dev
      - libyaml-dev
      - python3-apt
      - python3-setuptools
      - shellcheck
      - sshpass
      - tmux
      - vim
      - virtualenv
      - whois # for mkpasswrd

    ansible_pips:
      - ansible==9.1.0
      - ansible-lint==6.22.1

    rdp_packages:
      - rxvt-unicode
      - tigervnc-common
      - tigervnc-standalone-server
      - wmaker
      - xrdp

    editor_path: /usr/bin/vim.basic

  tasks:
    - name: Ensure minimum ansible version
      ansible.builtin.assert:
        that: ansible_version.full is version(minimum_ansible_version, '>=')
        fail_msg: Minimum ansible version required is {{ minimum_ansible_version }}
        quiet: true

    - name: Initial Packages
      ansible.builtin.package:
        name: '{{ packages }}'
        state: present
      become: true
      when: not ansible_check_mode
      # complains about python3-apt which is installed, but not in the
      # virtualenv
      tags:
        - ansible
        - package

    - name: Install Ansible
      ansible.builtin.pip:
        name: '{{ ansible_pips }}'
        virtualenv: '{{ ansible_user_dir }}/ansible'
        virtualenv_python: python3
        extra_args: --no-cache-dir --no-binary pyyaml
        # https://www.jeffgeerling.com/blog/2021/ansible-might-be-running-slow-if-libyaml-not-available
      tags:
        - ansible

    - name: RDP the Things
      ansible.builtin.package:
        name: '{{ rdp_packages }}'
        state: present
        install_recommends: false
      become: true
      when: not ansible_check_mode
      tags:
        - rdp

    - name: Remove Xorg section
      community.general.ini_file:
        path: /etc/xrdp/xrdp.ini
        section: Xorg
        state: absent
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Set vim as default editor
      community.general.alternatives:
        name: editor
        path: '{{ editor_path }}'
      become: true
      tags: ed

    - name: Set Window Maker as default X session
      ansible.builtin.file:
        path: '{{ ansible_user_dir }}/.xsession'
        state: link
        src: /usr/bin/wmaker
      tags:
        - rdp
        - wmaker
